sonar.projectKey=juice-shop
sonar.projectName=Juice Shop
sonar.projectVersion=1.0

# What to scan
sonar.sources=app.ts,server.ts,routes,lib,models,data,frontend/src
sonar.tests=test,frontend/src/app

# What NOT to scan
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,frontend/dist/**,frontend/node_modules/**,**/*.spec.ts,**/*.test.ts

# Language hints
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

# Test report locations (optional, will warn if missing)
sonar.javascript.lcov.reportPaths=build/reports/coverage/api-tests/lcov.info
